services:
    magentix_sylius_pickup_plugin.shop.layout.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@MagentixSyliusPickupPlugin/checkout/SelectShipping/pickup.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.javascripts, method: onBlockEvent }

    magentix_sylius_pickup_plugin.shop.layout.stylesheets:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@MagentixSyliusPickupPlugin/checkout/SelectShipping/stylesheets.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.stylesheets, method: onBlockEvent }

    magentix_sylius_pickup_plugin.order.initialize_complete:
        class: MagentixSyliusPickupPlugin\EventListener\OrderInitializeCompleteListener
        arguments:
            - "@sylius.registry.shipping_calculator"
            - "@sylius.repository.shipping_method"
            - "@sylius.repository.shipment"
        tags:
            - { name: kernel.event_listener, event: sylius.order.initialize_complete, method: updateShippingAddress }

    magentix_sylius_pickup_plugin.order.pre_complete:
        class: MagentixSyliusPickupPlugin\EventListener\OrderPreCompleteListener
        arguments:
            - "@sylius.registry.shipping_calculator"
            - "@sylius.repository.shipping_method"
            - "@sylius.repository.shipment"
            - "@sylius.factory.address"
        tags:
            - { name: kernel.event_listener, event: sylius.order.pre_complete, method: addShippingAddress }